// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package demo.beans.proto;

/**
 * Protobuf type {@code demo.beans.proto.MessageReply}
 */
public  final class MessageReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:demo.beans.proto.MessageReply)
        MessageReplyOrBuilder {
  // Use MessageReply.newBuilder() to construct.
  private MessageReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageReply() {
    success_ = 0;
    message_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MessageReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            success_ = rawValue;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return demo.beans.proto.DemoProto.internal_static_demo_beans_proto_MessageReply_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return demo.beans.proto.DemoProto.internal_static_demo_beans_proto_MessageReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            demo.beans.proto.MessageReply.class, demo.beans.proto.MessageReply.Builder.class);
  }

  /**
   * Protobuf enum {@code demo.beans.proto.MessageReply.EnumSuccess}
   */
  public enum EnumSuccess
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <code>KO = 1;</code>
     */
    KO(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>KO = 1;</code>
     */
    public static final int KO_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static EnumSuccess valueOf(int value) {
      return forNumber(value);
    }

    public static EnumSuccess forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return KO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnumSuccess>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EnumSuccess> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnumSuccess>() {
            public EnumSuccess findValueByNumber(int number) {
              return EnumSuccess.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return demo.beans.proto.MessageReply.getDescriptor().getEnumTypes().get(0);
    }

    private static final EnumSuccess[] VALUES = values();

    public static EnumSuccess valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EnumSuccess(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:demo.beans.proto.MessageReply.EnumSuccess)
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private int success_;
  /**
   * <code>.demo.beans.proto.MessageReply.EnumSuccess success = 1;</code>
   */
  public int getSuccessValue() {
    return success_;
  }
  /**
   * <code>.demo.beans.proto.MessageReply.EnumSuccess success = 1;</code>
   */
  public demo.beans.proto.MessageReply.EnumSuccess getSuccess() {
    demo.beans.proto.MessageReply.EnumSuccess result = demo.beans.proto.MessageReply.EnumSuccess.valueOf(success_);
    return result == null ? demo.beans.proto.MessageReply.EnumSuccess.UNRECOGNIZED : result;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile Object message_;
  /**
   * <code>string message = 2;</code>
   */
  public String getMessage() {
    Object ref = message_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    Object ref = message_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != demo.beans.proto.MessageReply.EnumSuccess.OK.getNumber()) {
      output.writeEnum(1, success_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != demo.beans.proto.MessageReply.EnumSuccess.OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, success_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof demo.beans.proto.MessageReply)) {
      return super.equals(obj);
    }
    demo.beans.proto.MessageReply other = (demo.beans.proto.MessageReply) obj;

    boolean result = true;
    result = result && success_ == other.success_;
    result = result && getMessage()
        .equals(other.getMessage());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + success_;
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static demo.beans.proto.MessageReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static demo.beans.proto.MessageReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static demo.beans.proto.MessageReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static demo.beans.proto.MessageReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static demo.beans.proto.MessageReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static demo.beans.proto.MessageReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static demo.beans.proto.MessageReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static demo.beans.proto.MessageReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static demo.beans.proto.MessageReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static demo.beans.proto.MessageReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static demo.beans.proto.MessageReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static demo.beans.proto.MessageReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(demo.beans.proto.MessageReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code demo.beans.proto.MessageReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:demo.beans.proto.MessageReply)
      demo.beans.proto.MessageReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return demo.beans.proto.DemoProto.internal_static_demo_beans_proto_MessageReply_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return demo.beans.proto.DemoProto.internal_static_demo_beans_proto_MessageReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              demo.beans.proto.MessageReply.class, demo.beans.proto.MessageReply.Builder.class);
    }

    // Construct using demo.beans.proto.MessageReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      success_ = 0;

      message_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return demo.beans.proto.DemoProto.internal_static_demo_beans_proto_MessageReply_descriptor;
    }

    public demo.beans.proto.MessageReply getDefaultInstanceForType() {
      return demo.beans.proto.MessageReply.getDefaultInstance();
    }

    public demo.beans.proto.MessageReply build() {
      demo.beans.proto.MessageReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public demo.beans.proto.MessageReply buildPartial() {
      demo.beans.proto.MessageReply result = new demo.beans.proto.MessageReply(this);
      result.success_ = success_;
      result.message_ = message_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof demo.beans.proto.MessageReply) {
        return mergeFrom((demo.beans.proto.MessageReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(demo.beans.proto.MessageReply other) {
      if (other == demo.beans.proto.MessageReply.getDefaultInstance()) return this;
      if (other.success_ != 0) {
        setSuccessValue(other.getSuccessValue());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      demo.beans.proto.MessageReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (demo.beans.proto.MessageReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int success_ = 0;
    /**
     * <code>.demo.beans.proto.MessageReply.EnumSuccess success = 1;</code>
     */
    public int getSuccessValue() {
      return success_;
    }
    /**
     * <code>.demo.beans.proto.MessageReply.EnumSuccess success = 1;</code>
     */
    public Builder setSuccessValue(int value) {
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.demo.beans.proto.MessageReply.EnumSuccess success = 1;</code>
     */
    public demo.beans.proto.MessageReply.EnumSuccess getSuccess() {
      demo.beans.proto.MessageReply.EnumSuccess result = demo.beans.proto.MessageReply.EnumSuccess.valueOf(success_);
      return result == null ? demo.beans.proto.MessageReply.EnumSuccess.UNRECOGNIZED : result;
    }
    /**
     * <code>.demo.beans.proto.MessageReply.EnumSuccess success = 1;</code>
     */
    public Builder setSuccess(demo.beans.proto.MessageReply.EnumSuccess value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      success_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.demo.beans.proto.MessageReply.EnumSuccess success = 1;</code>
     */
    public Builder clearSuccess() {
      
      success_ = 0;
      onChanged();
      return this;
    }

    private Object message_ = "";
    /**
     * <code>string message = 2;</code>
     */
    public String getMessage() {
      Object ref = message_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessage(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:demo.beans.proto.MessageReply)
  }

  // @@protoc_insertion_point(class_scope:demo.beans.proto.MessageReply)
  private static final demo.beans.proto.MessageReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new demo.beans.proto.MessageReply();
  }

  public static demo.beans.proto.MessageReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageReply>
      PARSER = new com.google.protobuf.AbstractParser<MessageReply>() {
    public MessageReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageReply> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<MessageReply> getParserForType() {
    return PARSER;
  }

  public demo.beans.proto.MessageReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

