// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package demo.beans.proto;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo.beans.proto.MessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
