// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package demo.beans.proto;

public interface MessageReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo.beans.proto.MessageReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.demo.beans.proto.MessageReply.EnumSuccess success = 1;</code>
   */
  int getSuccessValue();
  /**
   * <code>.demo.beans.proto.MessageReply.EnumSuccess success = 1;</code>
   */
  MessageReply.EnumSuccess getSuccess();

  /**
   * <code>string message = 2;</code>
   */
  String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
